spring:
  application:
    name: Arrafni
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${application.datasource.url}
    username: ${application.datasource.username}
    password: ${application.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  profiles:
    active: dev